name: churchnow
favicon: null
layout_spectrum: 0.8962
typography_spectrum: 0.21698
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#071321'
    - '#959aae'
    - '#c6cad6'
    - '#862721'
    - '#22768a'
  brandStrength: 0.3125
  lightness: 0.7526584770530462
  saturation: 0.5777165738400072
  rhythmicContrast: 0.3726817350834608
purpose: []
