name: churchnow
favicon: null
layout_spectrum: 0.8962
typography_spectrum: 0.07002523727715015
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dbdbdb'
    - '#dd9933'
    - '#00e300'
    - '#ff00a6'
  brandStrength: 0.5
  lightness: 0.7526584770530462
  saturation: 0.5777165738400072
  rhythmicContrast: 0.3726817350834608
purpose: []
