name: CHURCH NOW
favicon: null
layout_spectrum: 0.49718
typography_spectrum: 0.59463
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#071321'
    - '#959aae'
    - '#c6cad6'
    - '#862721'
    - '#22768a'
  brandStrength: 0.0625
  lightness: 0.7526584770530462
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
