typography_spectrum: 0.59463
color:
  brandColors:
    - '#071321'
    - '#959aae'
    - '#c6cad6'
    - '#862721'
    - '#22768a'
  brandStrength: 0
  lightness: 0.7526584770530462
  saturation: 0.375
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.67505
analytics:
  google: null
  facebook: null
  twitter: null
name: CHURCH NOW
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: CHURCH NOW
purpose: []
